# Generated by Django 5.0.2 on 2024-03-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Secundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.principal')),
            ],
        ),
    ]
